# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tattoo}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["zbelzer"]
  s.date = %q{2012-04-18}
  s.description = %q{Tattoo is a (very) simple tool to decorate text as links based off of regular expressions and url templates.}
  s.email = %q{zbelzer@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/tattoo.rb",
    "lib/tattoo/gun.rb",
    "lib/tattoo/ink.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/tattoo_spec.rb",
    "tattoo.gemspec"
  ]
  s.homepage = %q{http://github.com/zbelzer/tattoo}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Tattoo: Ink some mad links on everyday text}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

